# Generated by Django 3.1.3 on 2021-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
